### ISSUE TITLE
Inventory tracking

### ISSUE THREAD

**Issue by pral2a** [dyne/zenpub-client#11]
- [ ] USER - can add a resource on the inventory
- [ ] USER - can track the transfer of a resource to another agent zenroom
- [ ] USER - can track the production of a new resource
- [ ] USER - can track the consumption of a new resource
- [ ] USER - can track the usage of a resource
- [ ] USER - can trace back all activities that are connected to a particular resource
